# Pin npm packages by running ./bin/importmap

pin "application", preload: true
pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
pin "@hotwired/stimulus", to: "stimulus.min.js", preload: true
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js", preload: true
pin_all_from "app/javascript/controllers", under: "controllers"
pin "mammoth", to: "https://ga.jspm.io/npm:mammoth@1.8.0/lib/index.js"
pin "#lib/internal/streams/stream.js", to: "https://ga.jspm.io/npm:readable-stream@2.3.8/lib/internal/streams/stream-browser.js"
pin "#lib/", to: "https://ga.jspm.io/npm:mammoth@1.8.0/browser/"
pin "@xmldom/xmldom", to: "https://ga.jspm.io/npm:@xmldom/xmldom@0.8.10/lib/index.js"
pin "@xmldom/xmldom/lib/dom", to: "https://ga.jspm.io/npm:@xmldom/xmldom@0.8.10/lib/dom.js"
pin "base64-js", to: "https://ga.jspm.io/npm:base64-js@1.5.1/index.js"
pin "bluebird/js/release/promise", to: "https://ga.jspm.io/npm:bluebird@3.4.7/js/release/promise.js"
pin "buffer", to: "https://ga.jspm.io/npm:@jspm/core@2.1.0/nodelibs/browser/buffer.js"
pin "core-util-is", to: "https://ga.jspm.io/npm:core-util-is@1.0.3/lib/util.js"
pin "dingbat-to-unicode", to: "https://ga.jspm.io/npm:dingbat-to-unicode@1.0.1/dist/index.js"
pin "events", to: "https://ga.jspm.io/npm:@jspm/core@2.1.0/nodelibs/browser/events.js"
pin "immediate", to: "https://ga.jspm.io/npm:immediate@3.0.6/lib/browser.js"
pin "inherits", to: "https://ga.jspm.io/npm:inherits@2.0.4/inherits_browser.js"
pin "isarray", to: "https://ga.jspm.io/npm:isarray@1.0.0/index.js"
pin "jszip", to: "https://ga.jspm.io/npm:jszip@3.10.1/lib/index.js"
pin "lie", to: "https://ga.jspm.io/npm:lie@3.3.0/lib/browser.js"
pin "lop", to: "https://ga.jspm.io/npm:lop@0.4.1/index.js"
pin "option", to: "https://ga.jspm.io/npm:option@0.2.4/index.js"
pin "pako", to: "https://ga.jspm.io/npm:pako@1.0.11/index.js"
pin "process", to: "https://ga.jspm.io/npm:@jspm/core@2.1.0/nodelibs/browser/process-production.js"
pin "process-nextick-args", to: "https://ga.jspm.io/npm:process-nextick-args@2.0.1/index.js"
pin "readable-stream", to: "https://ga.jspm.io/npm:readable-stream@2.3.8/readable-browser.js"
pin "safe-buffer", to: "https://ga.jspm.io/npm:safe-buffer@5.1.2/index.js"
pin "setimmediate", to: "https://ga.jspm.io/npm:setimmediate@1.0.5/setImmediate.js"
pin "string_decoder", to: "https://ga.jspm.io/npm:string_decoder@1.1.1/lib/string_decoder.js"
pin "underscore", to: "https://ga.jspm.io/npm:underscore@1.13.7/modules/index-all.js"
pin "util", to: "https://ga.jspm.io/npm:@jspm/core@2.1.0/nodelibs/browser/util.js"
pin "util-deprecate", to: "https://ga.jspm.io/npm:util-deprecate@1.0.2/browser.js"
pin "xmlbuilder", to: "https://ga.jspm.io/npm:xmlbuilder@10.1.1/lib/index.js"
